owner: amn-nl # Your GitHub organization or username, where this repository lives
repo: status-page # The name of this repository
user-agent: bogdan-craciun
sites:
  - name: AMN website
    url: https://amn.nl
    icon: https://amn.nl/android-chrome-192x192.png
  - name: Insight application
    url: $INTAKE
    icon: https://cluster.amn.nl/favicon.ico
assignees:
  - bogdan-craciun

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.amn.nl
  # baseUrl: /status-page
  logoUrl: https://amn.nl/assets/images/logo-amn.svg
  name: AMN Status Page
  introTitle: ""
  introMessage: This is the status page of [AMN](https://amn.nl).
  favicon: https://amn.nl/android-chrome-192x192.png
  faviconSvg: https://amn.nl/assets/images/logo-amn.svg
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://amn.nl
    - title: Helpdesk
      href: https://amn.nl/help
    - title: Contact
      href: https://amn.nl/contactformulier

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
